services:
  server:
    build:
      context: .
      dockerfile: docker/server/dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/db/transparency.sqlite
    volumes:
      - db-data:/app/db
      - pdf-cache:/app/.cache
    ports:
      - "3000:3000"

  client:
    build:
      context: .
      dockerfile: docker/client/dockerfile
      args:
        VITE_API_BASE_URL: https://transparencycheck.app:3000 #This needs to be the live URL of the server you are hosting on
                                                             # If you don't have a URL, change this to http://localhost:3000 if running locally
                                                             # Or if running remotely with no url, change it to http://yourserverip:3000
    depends_on:
      - server
    ports:
      - "8080:80"  # Change to 8080:80 for production server
      # - "8443:443"

volumes:
  db-data:
  pdf-cache:
